version: '3.8'
services:
  database:
    container_name: database
    image: postgres:14-alpine
    restart: always
    env_file:
      - env_profile
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - net_backend

  backend:
    container_name: backend
    restart: always
    depends_on:
      database:
        condition: service_healthy
    build:
      context: ./lib_catalog/
      dockerfile: Dockerfile
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 30s
      timeout: 5s
      start_period: 20s
      retries: 5
    ports:
      - 8000:8000
    networks:
      - net_backend

networks:
  net_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.11.0/24
          gateway: 192.168.11.1
